### ISSUE TITLE
graph_node port-related errors when deleting a nested MultiEvent GraphNode

### ISSUE THREAD

**Issue by vabrador** [dog-on-moon/moon-interval#1]
Hi! I'm making a backport of this addon to Godot 4.2.2 (ongoing) and I hit this error that I can reproduce on `main`:

Godot: v4.3.beta3.official [82cedc83c] - Windows 11
Addon: `main` 7054823c

Deleting a graph node inside a MultiEvent contained inside another MultiEvent while the inner MultiEvent's outer-representation has connections to graph nodes in the outer MultiEvent causes error spam related to gui/graph_node. (Say that five times fast..)
```
  scene/gui/graph_node.cpp:763 - Index p_port_idx = 1 is out of bounds (right_port_cache.size() = 1).
  scene/gui/graph_node.cpp:753 - Index p_port_idx = 1 is out of bounds (right_port_cache.size() = 1).
  scene/gui/graph_node.cpp:772 - Index p_port_idx = 1 is out of bounds (right_port_cache.size() = 1).
```
I can produce this behavior with the following steps:
- open test_tscn.tscn -> EventPlayer's MultiEvent editor
- enter "everything all at once"
- delete the "Await Signal" node
- return to the parent MultiEvent
- get console error spam related to port indices out-of-bounds.

I'm guessing there's some cache invalidation that needs to happen when an inner MultiEvent gets modified, but I'm not certain.

Excited to use this addon, this code is really great.

**Comment by dog-on-moon** [comment]
In general I think there is an issue with graphedit2 where it doesn't properly disconnect events when the number of outputs shrink (a similar issue occurs with some routers), I'll look to patching this.
