### ISSUE TITLE
Issues with additional arguments when binding signals

### ISSUE THREAD

**Issue by cpazzra** [dog-on-moon/moon-interval#3]
Should note I'm using the dotnet version of godot, if that's important. But this seems like an issue with GDscript behavior.

Most noticeable if you use animation player nodes.

You'll see an error like this:

```
0:00:08:0637   emit_signalp: Error calling from signal 'done' to callable: 'Resource(multi_event.gd)::_end_branch': Method expected 3 arguments, but called with 4.
  <C++ Source>   core/object/object.cpp:1200 @ emit_signalp()
```

Using the animation player event as an example, you have this binding:
`animation_player.animation_finished.connect(done.emit, CONNECT_ONE_SHOT)`

Note that the `done` callable points to the `_end_branch()` function.

The problem, is that the `animation_finished` signal also includes a parameter for the animation name completed.

This means `_end_branch` will attempted be called as follows: `_end_branch(animation_name: StringName, event: Event, _owner: Node, _state: Dictionary)`

This can be circumvented with the animation player event by unbinding the parameter: `animation_player.animation_finished.connect(done.emit.unbind(1), CONNECT_ONE_SHOT)`

But, this issue persists the the signals event as well. But I don't think there's a way to generically unbind signal parameters, with my little knowledge of GDscript.

**Comment by dog-on-moon** [comment]
Ah good catch, this was a bit of a silly oversight. I also didn't know that unbind could work like that, very interesting. You're right that there is no way to generically unbind signal parameters, but I've come up with a workaround for the time being. Let me know if the latest release fixes these issues: https://github.com/dog-on-moon/godot-intervals/releases/tag/v1.0.1

**Comment by cpazzra** [comment]
Looks like this fixed it. Thanks!
