### ISSUE TITLE
animation player event not clearing signal connections once completed

### ISSUE THREAD

**Issue by cpazzra** [dog-on-moon/moon-interval#4]
### The problem:
Maybe related to changes for fixing #3
On repeat event plays, the event player would stop per-maturely. On digging a little deeper, I discovered that `_end_branch` was getting called multiple times for animation player events.

Debugging a bit more, I found that, only on repeat plays, the `animation_finished` signal would have multiple connections:
Checked by adding this to the events `_get_interval`
`var connections = animation_player.animation_finished.get_connections()`

### Current workaround:
A manual disconnect didn't seem to work for some reason:
```
var connections = animation_player.animation_finished.get_connections()
if connections.size() == 0:
    animation_player.animation_finished.disconnect(done.emit.unbind(1))
```
So instead, I just added a the same check before the signal binding.

**EDIT:
Figured out the proper method of disconnecting signals. This seems to work?
```
var connections = animation_player.animation_finished.get_connections()
if connections.size() != 0:
	animation_player.animation_finished.disconnect(done.emit)
animation_player.animation_finished.connect(done.emit.unbind(1), CONNECT_ONE_SHOT)
```

### Potential solution:
This signal connection should be cleaned up after the event has completed. Not sure if other events that use signals are experiencing the same issues, but have not seen anything yet.

**Comment by dog-on-moon** [comment]
Testing an event graph like this, I can't seem to replicate a growing connections array here (though I'm testing with 4.4dev2):

![image](https://github.com/user-attachments/assets/78dede82-1f9d-460e-983a-2f8f306af78f)

It's strange that it wouldn't be disconnecting at all since it is flagged as one-shot. Perhaps the event might not be finishing in the first place? (for example, if your animation is looping, it wouldn't be emitting animation_finished or the done signal at all)

**Comment by cpazzra** [comment]
Good point. I don't think my animation are set to loop, but maybe that was something I missed.

At the same time, though, the events in question play multiple animations along with some transforms in a row. And individually, they finish successfully. It's just when playing one after another that it becomes an issue. 
Still, will have to double check to be sure.

Should also say that my setup may be a little non-standard. I have multiple event players being ran under different conditions (never at the same time, it's all hoooked into the "finished" signal)

Can share sone screenshots for a better illustration when I have time.

**Comment by cpazzra** [comment]
Double checked and there was one or two animations that had linear loops. Disabling them seemed to fix it?
Going to go ahead and close this since It's no longer reproducible after this.

For future reference, here's roughly how the events in question are running animations.
![image](https://github.com/user-attachments/assets/d4276329-06c4-496a-9710-6b88ae00780b)
